[project]
name = "ai-eng-capstone"
version = "0.1.0"
description = ""
authors = [
    {name = "Shubham Jain",email = "shubhamjaintsj@gmail.com"}
]
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.10,<0.17.0)",
    "pytest (>=9.1.1,<10.0.0)"
]
